exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          [
            "--autofix", # Autofix JSONs
          ]
      - id: check-added-large-files
        args: ["--maxkb=1500"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.246'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
      - id: pylama
        name: pylama
        description: Run pylama linter on python files/directories.
        entry: pylama
        language: python
        types: [ "python" ]
